### ISSUE TITLE
USER STORY: TESTING

### ISSUE THREAD

**Issue by Pierreslag** [Pierreslag/fishingblog#16]
As a **developer** I can **test the webbapp* so that **it is free from bugs**

## Acceptance Criteria
 - Appeling and working front end.
 - CSS pass the CSS Validation Service.
 - Images works and loads without any problem.
 - Links should work and open in new tab.
 - Good lighthouse score.
 - Working backend.
 - Working django admin panel.

## Tasks
   - [ ] Test HTML in Validator.
   - [ ] Test CSS in Validator.
   - [ ] Manual link testing.
   - [ ] Google lighthouse testing.
   - [ ] Manual testing of Django admin panel and backend.

**Comment by Pierreslag** [comment]
Bugg when importing html page to validator, move to complete with 1 task left.
